Ext.define('KJERP.model.EquipmentItem',{
	extend:'Ext.data.TreeModel',
	fields:[{
		name:'vesselIdx'	,
		defaultValue:0
	},{
		name:'componentIdx'	
	},{
		name:'name'
	},{
		name:'model'
	},{
		name:'type'		
	},{
		name:'qty'
	},{
		name:'unitPrice'
	},{
		name:'price'
	},{
		name:'tax'
	},{
		name:'tag', convert:_FUNCTION.tagConverter	
	},{
		name:'serialNo',
		defaultValue:''
	},{
		name:'remark',
		defaultValue:''
	},{
      	name:'equipmentItemIdx'
    },{
    	name:'dwOrder'
	},{
		name:'dwApproveState'
	},{
		name:'dwApproveDate'
	},{
		name:'dwApproveComment'
	},{
		name:'dwApproveFiles'
	},{
		name:'dwApproveUser'
	},{
		name:'dwWorkingState'
	},{
		name:'dwWorkingDate'
	},{
		name:'dwWorkingComment'
	},{
		name:'dwWorkingUser'
	},{
		name:'dwWorkingFiles'
	},{
		name:'dwFinalState'
	},{
		name:'dwFinalDate'
	},{
		name:'dwFinalComment'
	},{
		name:'dwFinalUser'		
	},{
		name:'dwFinalFiles'
	},{
		name:'reportFiles', defaultValue:[]		
	},
	'RDATE','RUSER','EDATE','EUSER'
	]
});